name: CI
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: docker image
      run: |
        docker build -t docker.vidyard.com/staging-shipit-paulli:${GITHUB_SHA} .
        docker push docker.vidyard.com/staging-shipit-paulli:${GITHUB_SHA}
